grpc_port: ":50051"
jwt_secret: "your-secret-key"
ssl_cert: "cert.pem"
ssl_key: "key.pem"
db_host: "ep-wandering-rice-a2vdznr6-pooler.eu-central-1.aws.neon.tech"
db_port: "5432"
db_user: "default"
db_password: "QkwmOzS2pMD7"
db_name: "verceldb"
mail_from: "refrefrefrefref123@gmail.com"
mail_password: "nxy_*8135X"
smtp_host: "smtp.gmail.com"
smtp_port: "587"