grpc_port: ":50051"
jwt_secret: "your-secret-key"
ssl_cert: "cert.pem"
ssl_key: "key.pem"
db_host: "ep-icy-rain-a2uhdp00-pooler.eu-central-1.aws.neon.tech"
db_port: "5432"
db_user: "default"
db_password: "Vl91hQbdHvMw"
db_name: "verceldb"
mail_from: "refrefrefrefref123@gmail.com"
mail_password: "mvon pkni gjsy rfyw"
smtp_host: "smtp.gmail.com"
smtp_port: "587"
rest_port: ":8080"
google_client_id: "697503104115-ui1i318hgo5h9d439tanq51s6gtc3pd8.apps.googleusercontent.com"
googel_client_secret: "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"
twilio_account_sid: "AC192d17cd0792f1aa5dd021bd5bd9c8e0"
twilio_auth_token: "7982fe2932b9d92704c0b4b80936fba4"
twilio_phone_number: "+12673411084"
to_phone_number: "+375291555074"